services:
    nietzscheson.fixtures_factory.array_resolver:
        class: Nietzscheson\FixturesFactoryBundle\Fixtures\ArrayResolver
        arguments:
            - '@kernel'
            - '%kernel.bundles%'
            - '@hautelook_alice.locator.environmentless'
        public: false

    nietzscheson.fixtures_factory:
        class: Nietzscheson\FixturesFactoryBundle\Fixtures\Factory
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@nietzscheson.fixtures_factory.array_resolver'
            - '@nelmio_alice.data_loader.simple'
