services:
    nietzcheson.fixtures_factory.array_resolver:
        class: Nietzcheson\FixturesFactoryBundle\Fixtures\ArrayResolver
        arguments:
            - '@kernel'
            - '%kernel.bundles%'
            - '@hautelook_alice.locator.environmentless'

    nietzcheson.fixtures_factory:
        class: Nietzcheson\FixturesFactoryBundle\Fixtures\Factory
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@nietzcheson.fixtures_factory.array_resolver'
            - '@nelmio_alice.data_loader.simple'
